### ISSUE TITLE
Post Status Every Day at Given Time

### ISSUE THREAD

**Issue by mutewinter** [postlight/hubot-pingboard#1]
In a room specified by an environment variable.

Perhaps using a URL that can be hit by an IFTT script.

**Comment by mutewinter** [comment]
Done in https://github.com/postlight/hubot-pingboard/commit/1e69d9ee65c93813e931a7bb49448d8e42a17dff

**Comment by closacco** [comment]
@mutewinter Where's the "at a given time" piece?
